# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: "en"
early_access: false

reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  review_status: true
  review_details: true
  collapse_walkthrough: true

  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - master
      - develop

  path_filters:
    - "src/**"
    - "src-tauri/**"
    - "**/*.ts"
    - "**/*.tsx"
    - "**/*.rs"
    - "tauri.conf.json"
    - "Cargo.toml"
    - "package.json"
    - "!node_modules/**"
    - "!dist/**"
    - "!build/**"
    - "!target/**"
    - "!**/*.lock"
    - "!**/*.min.*"

  labeling_instructions:
    - label: "bug"
      instructions: "Identifies defects or unexpected behavior."
    - label: "security"
      instructions: "Indicates security or permission issues."
    - label: "performance"
      instructions: "Indicates performance regressions or inefficiencies."
    - label: "refactor"
      instructions: "Structural changes without external behavior changes."
    - label: "enhancement"
      instructions: "Adds new functionality or improves existing behavior."
    - label: "documentation"
      instructions: "Documentation updates or improvements."
    - label: "dependencies"
      instructions: "Updates dependency versions or related config."
    - label: "frontend"
      instructions: "Front-end related changes like UI, TS, React."
    - label: "rust"
      instructions: "Rust backend changes in src-tauri."
    - label: "tauri"
      instructions: "Tauri specific configuration or capability changes."

  path_instructions:
    - path: "src-tauri/**/*.rs"
      instructions: "Check Rust error handling and avoid unwrap()."
    - path: "src/**/*.{ts,tsx}"
      instructions: "Check React hook usage and TypeScript type safety."
    - path: "tauri.conf.json"
      instructions: "Verify Tauri config and permission settings."

  instructions: "Review code with priority on correctness, security, and consistency."

chat:
  auto_reply: true
  art: false

issue_enrichment:
  auto_enrich:
    enabled: true
  planning:
    enabled: true
  labeling:
    enabled: true

tools:
  ast-grep:
    essential_rules: true
  shellcheck:
    enabled: true
