# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: "en"
early_access: false

reviews:
  profile: "assertive"
  request_changes_workflow: false

  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  review_status: true
  review_details: true
  collapse_walkthrough: true
  poem: false

  auto_review:
    enabled: true
    drafts: false
    base_branches: [ main, master, develop ]

  path_filters:
    - "src/**"
    - "src-tauri/**"
    - "**/*.ts"
    - "**/*.tsx"
    - "**/*.rs"
    - "tauri.conf.json"
    - "Cargo.toml"
    - "package.json"

    - "!node_modules/**"
    - "!dist/**"
    - "!build/**"
    - "!target/**"
    - "!**/*.lock"
    - "!**/*.min.*"

  labeling_instructions:
    bug:
      instructions: "Incorrect behavior, crashes, logic errors, panics, memory issues."

    security:
      instructions: "Auth, permission, input validation, unsafe operations, secrets."

    performance:
      instructions: "Inefficient algorithms, unnecessary allocations, blocking operations."

    refactor:
      instructions: "Structural improvements without behavior change."

    enhancement:
      instructions: "New features or extensions."

    documentation:
      instructions: "Docs, comments, README, API explanations."

    rust:
      instructions: "Changes in Rust backend or src-tauri."

    frontend:
      instructions: "React, TypeScript, UI related changes."

    tauri:
      instructions: "Tauri config, capabilities, commands."

  instructions: |
    ## Mandatory Review Checklist

    ### Rust / Tauri
    - No unwrap() or expect() in non-test code
    - Proper Result and error propagation
    - Validate command permissions and capabilities
    - Cross-platform compatibility

    ### Frontend
    - No implicit any
    - Hooks dependency correctness
    - Avoid unnecessary re-renders
    - Accessibility basics (aria, keyboard)

    ### General
    - Security before performance
    - Config changes must be validated
    - Avoid silent failure patterns
    - Prefer explicit over implicit

chat:
  auto_reply: true
  art: false

issue_enrichment:
  auto_enrich:
    enabled: true
    only_labels: [ bug, security ]

  planning:
    enabled: true

  labeling:
    enabled: true

tools:
  ast-grep:
    essential_rules: true

  shellcheck:
    enabled: true
