# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: "en"
early_access: false

reviews:
  profile: "assertive"
  request_changes_workflow: false

  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  poem: false
  review_status: true
  review_details: true
  collapse_walkthrough: true

  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - master
      - develop

  path_filters:
    - "src/**"
    - "src-tauri/**"
    - "**/*.ts"
    - "**/*.tsx"
    - "**/*.rs"
    - "tauri.conf.json"
    - "Cargo.toml"
    - "package.json"

    - "!node_modules/**"
    - "!dist/**"
    - "!build/**"
    - "!target/**"
    - "!**/*.lock"
    - "!**/*.min.*"

  labeling_instructions:
    - label: "bug"
      instructions: "Fix defects, incorrect logic, crashes, or runtime errors."

    - label: "security"
      instructions: "Address security issues such as permissions, validation, secrets, or unsafe code."

    - label: "performance"
      instructions: "Improve performance, memory usage, or execution efficiency."

    - label: "refactor"
      instructions: "Refactor code structure without changing external behavior."

    - label: "enhancement"
      instructions: "Add new features or extend existing functionality."

    - label: "documentation"
      instructions: "Update or improve documentation or code comments."

    - label: "dependencies"
      instructions: "Update or modify dependency versions or configuration."

    - label: "frontend"
      instructions: "Changes related to frontend code such as React, TypeScript, or CSS."

    - label: "rust"
      instructions: "Changes related to Rust backend or src-tauri code."

    - label: "tauri"
      instructions: "Changes related to Tauri configuration, capabilities, or commands."

  path_instructions:
    - path: "src-tauri/**/*.rs"
      instructions: "Review Rust memory safety, error handling, and avoid unwrap or expect."

    - path: "src/**/*.{ts,tsx}"
      instructions: "Review TypeScript type safety, React hooks usage, and component performance."

    - path: "tauri.conf.json"
      instructions: "Verify Tauri configuration correctness and security permissions."

  instructions: |
    Review the code carefully with priority on security, correctness, and configuration safety.
    Avoid unwrap or expect in production Rust code.
    Validate permissions and capabilities in Tauri.
    Prefer explicit error handling and clear logic.

chat:
  auto_reply: true
  art: false

issue_enrichment:
  auto_enrich:
    enabled: true

  planning:
    enabled: true

  labeling:
    enabled: true

tools:
  ast-grep:
    essential_rules: true

  shellcheck:
    enabled: true
